/dynamics_simulator:
  ros__parameters:
    l_f: 0.8 # m
    l_r: 0.7 # m
    m: 220.0 # kg
    Iz: 100.0 # kg m m
    g: 9.81 # m s-2
    D_tire: -1.0
    C_tire: 1.4
    B_tire: 9.5
    C_d: 1.133 # 0.5 * rho * CdA
    C_r: 0.5 # -
    T_mot:  0.01 # s
    D_mot:  1.0 # -
    gamma: 1.2 # rad  
    r_perception_max: 25.0 # m
    r_perception_min: 2.0 # m
    track_filepath_midline: "src/sim_backend/tracks/FSG_middle_path.csv"
    track_filepath_leftbound: "src/sim_backend/tracks/FSG_blue_cones.csv"
    track_filepath_rightbound: "src/sim_backend/tracks/FSG_yellow_cones.csv"
    # track_filepath_midline: "src/sim_backend/tracks/circular_track_middle_path.csv"
    # track_filepath_leftbound: "src/sim_backend/tracks/circular_track_blue_cones.csv"
    # track_filepath_rightbound: "src/sim_backend/tracks/circular_track_yellow_cones.csv"
    # track_filepath_midline: "src/sim_backend/tracks/straight_track_middle_path.csv"
    # track_filepath_leftbound: "src/sim_backend/tracks/straight_track_blue_cones.csv"
    # track_filepath_rightbound: "src/sim_backend/tracks/straight_track_yellow_cones.csv"