/mpc_controller_node:
  ros__parameters:
    use_sim_time: true
    max_distance_path_points: 5.0
    dt_ms: 25
    model:
      l_f: 0.8 # m
      l_r: 0.7 # m
      m: 220.0 # kg
      C_d: 1.133 # 0.5 * rho * CdA
      C_r: 0.5 # -
      kappa_ref: 0.0
    horizon:
      T_final: 1.0
      N_horizon: 40
    cost:
      q_sd: 0.15
      q_n: 0.4
      q_mu: 0.01
      r_dels: 1.0
      r_ax: 0.01
      slack_penalties:
        linear:
          S_n_lin: 10.0
          S_n_lin_e: 100.0
          S_mu_lin: 10.0
          S_mu_lin_e: 100.0
        quadratic:
          S_n_quad: 100.0
          S_n_quad_e: 100.0
          S_mu_quad: 100.0
          S_mu_quad_e: 100.0
    constraints:
      soft:
        lb_n: -0.3
        ub_n: 0.3
        lb_mu: -0.5
        ub_mu: 0.5
      hard:
        lb_s: -10.0
        ub_s: 15.0
        lb_vx: 0.0
        ub_vx: 10.0
        lb_axm: -9.0
        ub_axm: 9.0
        lb_dels: -0.5
        ub_dels: 0.5
    solver_options:
      qp_solver: 'PARTIAL_CONDENSING_HPIPM' #'FULL_CONDENSING_HPIPM' #'FULL_CONDENSING_QPOASES' #'PARTIAL_CONDENSING_HPIPM'
      hessian_approx: 'EXACT' #'GAUSS_NEWTON' #'EXACT' #
      integrator_type: 'ERK'
      sim_method_newton_iter: 20
      nlp_solver_max_iter: 10
      qp_solver_iter_max: 50
      qp_solver_warm_start: 0
      regularize_method: 'PROJECT'
      reg_epsilon: 0.0001
      alpha_min: 0.000001
      alpha_reduction: 0.7
      hpipm_mode: 'BALANCE' #'BALANCE', 'ROBUST', 'SPEED'
      cost_discretization: 'EULER'
      globalization: 'FIXED_STEP' # MERIT_BACKTRACKING  FIXED_STEP
      levenberg_marquardt: 0.0
      nlp_solver_step_length: 1.0
      tol: 0.01
      qp_tol: 0.00001
      init_rti_phase: 0