/mpc_controller:
  ros__parameters:
    model:
      l_f: 0.8 # m
      l_r: 0.7 # m
      m: 220.0 # kg
      Iz: 100.0 # kg m m
      g: 9.81 # m s-2
      D_tire: -1.0
      C_tire: 1.4
      B_tire: 9.5
      C_d: 1.133 # 0.5 * rho * CdA
      C_r: 0.5 # -
      blending_factor: 0.0
      kappa_ref: 0.05
    horizon:
      T_final: 1.0
      N_horizon: 40
      n_s: 40
      s_max: 20.0
    cost:
      r_dFx: 0.000001
      r_del_s: 10.0
      q_beta: 300.0
      q_sd: 1.0
      q_del: 5.0
      q_n: 5.0
      q_r_e: 1000.0
      q_mu_e: 1.0
      q_n_e: 100.0
      slack_penalties:
        linear:
          S_n_lin: 100.0
          S_vx_lin: 0.1
          S_te_lin: 5000.0
          S_n_lin_e: 100.0
          S_vx_lin_e: 500.0
          S_te_lin_e: 5000.0
        quadratic:
          S_n_quad: 300.0
          S_vx_quad: 0.1
          S_te_quad: 2000.0
          S_n_quad_e: 300.0
          S_vx_quad_e: 1.0
          S_te_quad_e: 2000.0
    constraints:
      soft:
        e_x_front: 1.2
        e_x_rear: 1.2
        e_y_front: 1.2
        e_y_rear: 1.2
        n_max: 3.0
        n_min: -3.0
        L_F: 0.97
        L_R: 0.85
        W: 2.0
        vx_max: 10.0
        vx_max_e: 5.0
      hard:
        lb_h: -1000000000000000.0
        ub_h: 0.0
        lb_u_dFx: -1000.0
        ub_u_dFx: 1000.0
        lb_u_ddels: -2.0
        ub_u_ddels: 2.0
        lb_x_n: -100.0
        ub_x_n: 100.0
        lb_x_mu: -2.0
        ub_x_mu: 2.0
        lb_x_vx: -0.1
        ub_x_vx: 100.0
        lb_x_vy: -5.0
        ub_x_vy: 5.0
        lb_x_dpsi: -5.0
        ub_x_dpsi: 5.0
        lb_x_Fx: -3000.0
        ub_x_Fx: 3000.0
        lb_x_dels: -1.5
        ub_x_dels: 1.5
    solver_options:
      qp_solver: 'PARTIAL_CONDENSING_HPIPM' # FULL_CONDENSING_QPOASES
      hessian_approx: 'EXACT' #'GAUSS_NEWTON'
      integrator_type: 'IRK'
      sim_method_newton_iter: 20
      nlp_solver_max_iter: 100
      qp_solver_iter_max: 50
      tol: 0.01
      qp_tol: 0.001