/mpc_controller_node:
  ros__parameters:
    use_sim_time: true
    model:
      l_f: 0.8 # m
      l_r: 0.7 # m
      m: 220.0 # kg
      Iz: 100.0 # kg m m
      g: 9.81 # m s-2
      D_tire: -3.0
      C_tire: 1.0
      B_tire: 9.0
      C_d: 1.133 # 0.5 * rho * CdA
      C_l: 3.0
      C_r: 0.5 # -
      kappa_ref: 0.0
    horizon:
      T_final: 1.0
      N_horizon: 40
      n_s: 30
      s_max: 15.0
    cost:
      q_sd: 1.0
      q_n: 1.0
      q_mu: 0.5
      q_vy: 0.01
      q_dpsi: 0.01
      r_dels: 0.001
      r_ax: 0.0001
      slack_penalties:
        linear:
          S_n_lin: 1.0
          S_n_lin_e: 1.0
          S_mu_lin: 0.1
          S_mu_lin_e: 0.0
          S_vy_lin: 0.1
          S_vy_lin_e: 0.0
          S_dpsi_lin: 0.1
          S_dpsi_lin_e: 0.0
        quadratic:
          S_n_quad: 5.0
          S_n_quad_e: 5.0
          S_mu_quad: 2.0
          S_mu_quad_e: 2.0
          S_vy_quad: 1.0
          S_vy_quad_e: 1.0
          S_dpsi_quad: 1.0
          S_dpsi_quad_e: 1.0
    constraints:
      soft:
        lb_n: -1.0
        ub_n: 1.0
        lb_mu: -0.7
        ub_mu: 0.7
        lb_vx: 0.0
        ub_vx: 10.0
        lb_vy: -4.0
        ub_vy: 4.0
        lb_dpsi: -2.0
        ub_dpsi: 2.0
      hard:
        lb_s: -0.1
        ub_s: 40.0
        lb_axm: -10.0
        ub_axm: 10.0
        lb_dels: -0.6
        ub_dels: 0.6
    solver_options:
      qp_solver: 'PARTIAL_CONDENSING_HPIPM' #'FULL_CONDENSING_HPIPM' #'FULL_CONDENSING_QPOASES' #'PARTIAL_CONDENSING_HPIPM'
      hessian_approx: 'EXACT' #'GAUSS_NEWTON' #'EXACT' #
      integrator_type: 'IRK'
      sim_method_newton_iter: 20
      nlp_solver_max_iter: 10
      qp_solver_iter_max: 50
      qp_solver_warm_start: 1
      regularize_method: 'PROJECT'
      reg_epsilon: 0.000000001
      alpha_min: 0.0001
      alpha_reduction: 0.7
      hpipm_mode: 'BALANCE' #'BALANCE', 'ROBUST', 'SPEED'
      cost_discretization: 'EULER'
      globalization: 'FIXED_STEP' # MERIT_BACKTRACKING  FIXED_STEP
      levenberg_marquardt: 0.0
      nlp_solver_step_length: 1.0
      tol: 0.001
      qp_tol: 0.00001