/mpc_controller_node:
  ros__parameters:
    model:
      l_f: 0.8 # m
      l_r: 0.7 # m
      m: 220.0 # kg
      Iz: 100.0 # kg m m
      g: 9.81 # m s-2
      D_tire: -1.0
      C_tire: 1.4
      B_tire: 9.5
      C_d: 1.133 # 0.5 * rho * CdA
      C_r: 0.5 # -
      kappa_ref: 0.0
    horizon:
      T_final: 1.0
      N_horizon: 40
      n_s: 30
      s_max: 15.0
    cost:
      q_sd: 1.0
      slack_penalties:
        linear:
          S_n_lin: 10.0
          S_n_lin_e: 10.0
          S_mu_lin: 1.0
          S_mu_lin_e: 1.0
          S_vx_lin: 20.0
          S_vx_lin_e: 20.0
          S_vy_lin: 1.0
          S_vy_lin_e: 1.0
          S_dpsi_lin: 1.0
          S_dpsi_lin_e: 1.0
        quadratic:
          S_n_quad: 10.0
          S_n_quad_e: 10.0
          S_mu_quad: 1.0
          S_mu_quad_e: 1.0
          S_vx_quad: 3.0
          S_vx_quad_e: 3.0
          S_vy_quad: 1.0
          S_vy_quad_e: 1.0
          S_dpsi_quad: 1.0
          S_dpsi_quad_e: 1.0
    constraints:
      soft:
        lb_n: -1.0
        ub_n: 1.0
        lb_mu: -1.5
        ub_mu: 1.5
        lb_vx: -0.1
        ub_vx: 15.0
        lb_vy: -2.0
        ub_vy: 2.0
        lb_dpsi: -3.0
        ub_dpsi: 3.0
      hard:
        lb_s: -0.1
        ub_s: 100.0
        lb_Fxm: -2000.0
        ub_Fxm: 2000.0
        lb_dels: -1.5
        ub_dels: 1.5
    solver_options:
      qp_solver: 'PARTIAL_CONDENSING_HPIPM' #'FULL_CONDENSING_HPIPM' #'FULL_CONDENSING_QPOASES' #'PARTIAL_CONDENSING_HPIPM'
      hessian_approx: 'EXACT' #'GAUSS_NEWTON' #'EXACT' #
      integrator_type: 'IRK'
      sim_method_newton_iter: 20
      nlp_solver_max_iter: 100
      qp_solver_iter_max: 50
      qp_solver_warm_start: 1
      regularize_method: 'MIRROR'
      reg_epsilon: 0.0000000001
      alpha_min: 0.05
      alpha_reduction: 0.7
      hpipm_mode: 'BALANCE' #'BALANCE', 'ROBUST', 'SPEED'
      cost_discretization: 'EULER'
      tol: 0.01
      qp_tol: 0.00001