/mpc_controller_node:
  ros__parameters:
    model:
      l_f: 0.8 # m
      l_r: 0.7 # m
      m: 220.0 # kg
      Iz: 100.0 # kg m m
      g: 9.81 # m s-2
      D_tire: -1.0
      C_tire: 1.4
      B_tire: 9.5
      C_d: 1.133 # 0.5 * rho * CdA
      C_r: 0.5 # -
      kappa_ref: 0.0
    horizon:
      T_final: 1.0
      N_horizon: 40
      n_s: 30
      s_max: 15.0
    cost:
      q_sd: 1.0
      slack_penalties:
        linear:
          S_n_lin: 0.1
          S_n_lin_e: 1.0
        quadratic:
          S_n_quad: 0.1
          S_n_quad_e: 1.0
    constraints:
      soft:
        lb_n: -5.0
        ub_n: 5.0
      hard:
        lb_vx: -0.1
        ub_vx: 10.0
        lb_Fxm: -3000.0
        ub_Fxm: 3000.0
        lb_dels: -1.5
        ub_dels: 1.5
    solver_options:
      qp_solver: 'FULL_CONDENSING_HPIPM' #'FULL_CONDENSING_QPOASES' #'PARTIAL_CONDENSING_HPIPM'
      hessian_approx: 'EXACT' #'GAUSS_NEWTON' #'EXACT' #
      integrator_type: 'IRK'
      sim_method_newton_iter: 20
      nlp_solver_max_iter: 100
      qp_solver_iter_max: 50
      qp_solver_warm_start: 1
      alpha_min: 0.05
      tol: 0.01
      qp_tol: 0.01